#!/bin/bash

quiet=0
project="/home/ek/wgmn/frigbot"

test_flag=""
for arg in "$@"; do
  if [[ "$arg" == -* ]]; then
     [[ "$arg" == *"q"* ]] && quiet=1
     [[ "$arg" == *"t"* ]] && test_flag="-t"
  fi
done

if [[ $quiet -eq 1 ]]; then
    #nohup $pypath $project/$name $test_flag > ~/frigout.log 2> ~/frigerr.log 2>&1 &
    sudo systemctl start --now frigbot.service
    echo "Starting frigbot daemon"
else
    #$pypath $project/$name $test_flag
    "$project/.venv/bin/python" "$project/run.py" $test_flag
fi
