[project]
name = "frigbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.109.1",
    "requests>=2.32.5",
]
